"""
This script how to generate a mitmproxy dump file,
as it would also be generated by passing `-w` to mitmproxy.
In contrast to `-w`, this gives you full control over which
flows should be saved and also allows you to rotate files or log
to multiple files in parallel.
"""

import sys
from mitmproxy import io, http
from mitmproxy import flowfilter
import typing  # noqa
import logging

logHandler = logging.FileHandler('/python/wechat_proxy/wechat.log')
logger = logging.getLogger('mitmproxy')
logger.addHandler(logHandler)
logger.setLevel(logging.DEBUG)


class ArticleDataHandler(object):
    def save(self):
        pass


class ArticleContentHandler(object):
    def save(self):
        pass


class ArticleListHandler(object):
    def save(self):
        pass


def getHandler(flow):
    #
    if flow.path.startswith("/mp/getappmsgext"):
        return ArticleDataHandler()
    elif flow.path.startswith("/s?__biz"):
        return ArticleContentHandler()
    elif flow.path.startswith("/mp/profile_ext"):
        return ArticleListHandler()


def response(flow):
    handler = getHandler(flow)
    handler.save()
